services:
  postgres:
    image: postgres:17-alpine
    container_name: vk-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: vk
      POSTGRES_USER: vk
      POSTGRES_PASSWORD: vk_secret
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vk -d vk"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: vk-redis
    restart: unless-stopped
    ports:
      - "6380:6379"
    volumes:
     - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data:
